// import localFont from "next/font/local";
import { auth } from "../auth";
import Sidemenu from "./components/Sidemenu";
import "./globals.css";
import { Merriweather, Source_Sans_3 } from "next/font/google";
import StoreProvider from "./StoreProvider";
import { SessionProvider } from "next-auth/react";
import { redirect } from "next/navigation";
import ThemeProvider from "./ThemeProvider";


// const crimson_test = Merriweather({
//   weight: ["300", "700", "900"],
//   subsets: ["latin"],
// });

const open_sans_font = Source_Sans_3({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sain Packaging",
  description: "Generated by the Great",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  // console.table(session);

  return (
    <html lang="en">
      <SessionProvider session={children.session}>
        <StoreProvider>
          <body className={open_sans_font.className}>
            <ThemeProvider>
              {session && session ? (
                <>
                  <Sidemenu />
                  <div className="layoutRightDiv">{children}</div>
                </>
              ) : (
                <div className="layoutRightDivSignin">{children}</div>
              )}
            </ThemeProvider>
          </body>
        </StoreProvider>
      </SessionProvider>
    </html>
  );
}
